
### Hi there 👋

I am Donia, a Golang software developer geeking about cloud stuff. My last addiction is contributing to Open Source projects (thanks to [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/)). I currently dabble in blogging on [Medium](https://medium.com/@doniacld). Promoting women in tech is one of my preoccupation so I closely follow organisations like [50InTech](https://www.50intech.com/) and [GirlsInTech](https://girlsintech.org/).

When I am AFK, you can find me swing dancing, sewing or hiking !

<img alt="Github Stats" src="https://github-readme-stats.vercel.app/api?username=doniacld&show_icons=true&count_private=true&hide=stars&include_all_commits=true&theme=vue" align="right" />

### 🔭 My last contributions

{{range recentContributions 5}}
- [{{.Repo.Name}}]({{.Repo.URL}})
{{- end}}

  <br>
</div>

### :black_nib: My recent blog posts (and only one for the moment)

<br> <a target="_blank" href="https://github-readme-medium-recent-article.vercel.app/medium/@doniacld/0"><img src="https://github-readme-medium-recent-article.vercel.app/medium/@doniacld/0" alt="Recent Article 0"></a>
<br> <a target="_blank" href="https://github-readme-medium-recent-article.vercel.app/medium/@doniacld/1"><img src="https://github-readme-medium-recent-article.vercel.app/medium/@doniacld/1" alt="Recent Article 1"></a>
<br> <a target="_blank" href="https://github-readme-medium-recent-article.vercel.app/medium/@doniacld/2"><img src="https://github-readme-medium-recent-article.vercel.app/medium/@doniacld/2" alt="Recent Article 1"></a>
_(Generated by [Medium's Recent Article](https://github.com/bxcodec/github-readme-medium-recent-article))_

### 📫 How to reach me
- LinkedIn: https://www.linkedin.com/in/donia-chaiehloudj/
- Medium: https://doniacld.medium.com/
